//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralniDirektor
    {
        public int BrCK { get; set; }
        public int US { get; set; }
    
        public virtual ClanUpravnogOdbora ClanUpravnogOdbora { get; set; }
    }
}
