//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreningView
    {
        public long JMBG { get; set; }
        public string IP { get; set; }
        public string KA { get; set; }
        public System.DateTime DR { get; set; }
        public int IdKlub { get; set; }
        public int IdSD { get; set; }
        public int IdTR { get; set; }
        public System.TimeSpan TR { get; set; }
        public string OT { get; set; }
        public int IdT { get; set; }
        public long JMBGTR { get; set; }
        public long JMBGI { get; set; }
        public long JMBGT { get; set; }
        public string IiP { get; set; }
        public int BRT { get; set; }
        public string KAR { get; set; }
        public int IdKL { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
        public string LOK { get; set; }
        public string IST { get; set; }
        public long KAP { get; set; }
        public string NAZ { get; set; }
        public int IdK { get; set; }
        public int Expr3 { get; set; }
    }
}
