//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vlada
    {
        public Nullable<int> IdU { get; set; }
        public int IdSD { get; set; }
        public int IdVlada { get; set; }
    
        public virtual SD SD { get; set; }
        public virtual Uprava Uprava { get; set; }
    }
}
